In [ ]:
#Import
import pandas as pd
import numpy as np
from sklearn import svm 
import matplotlib.pyplot as plt

from matplotlib import style
style.use("ggplot")

# Read the CSV and Perform Basic Data Cleaning

In [2]:
#Import CSV 
df = pd.read_csv("cumulative_copy.csv")
df = df.drop(columns=["rowid", "kepid", "kepoi_name", "kepler_name", "koi_pdisposition", "koi_score", "koi_tce_delivname"])
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0       CONFIRMED              0              0              0              0   
1       CONFIRMED              0              0              0              0   
2  FALSE POSITIVE              0              1              0              0   
3  FALSE POSITIVE              0              1              0              0   
4       CONFIRMED              0              0              0              0   

   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \
0    9.488036     2.775000e-05    -2.775000e-05   170.538750   
1   54.418383     2.479000e-04    -2.479000e-04   162.513840   
2   19.899140     1.494000e-05    -1.494000e-05   175.850252   
3    1.736952     2.630000e-07    -2.630000e-07   170.307565   
4    2.525592     3.761000e-06    -3.761000e-06   171.595550   

   koi_time0bk_err1     ...      koi_steff_err2  koi_slogg  koi_slogg_err1  \
0          0.002160     ...               -81.0      4.467           0.064   
1          0.003520     ...               -81.0      4.467           0.064   
2          0.000581     ...              -176.0      4.544           0.044   
3          0.000115     ...              -174.0      4.564           0.053   
4          0.001130     ...              -211.0      4.438           0.070   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.096     0.927          0.105         -0.061  291.93423   
2          -0.176     0.868          0.233         -0.078  297.00482   
3          -0.168     0.791          0.201         -0.067  285.53461   
4          -0.210     1.046          0.334         -0.133  288.75488   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.141651      15.347  
2  48.134129      15.436  
3  48.285210      15.597  
4  48.226200      15.509  

[5 rows x 41 columns]

# Create a Train Test Split

Use `koi_disposition` for the y values

In [3]:
#Y VALUES
target = df["koi_disposition"]
target_names = ["CONFIRMED", "FALSE POSITIVE"]

In [4]:
#X Values
data = df.drop("koi_disposition", axis=1)
feature_names = data.columns
data.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
0              0              0              0              0    9.488036   
1              0              0              0              0   54.418383   
2              0              1              0              0   19.899140   
3              0              1              0              0    1.736952   
4              0              0              0              0    2.525592   

   koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
0     2.775000e-05    -2.775000e-05   170.538750          0.002160   
1     2.479000e-04    -2.479000e-04   162.513840          0.003520   
2     1.494000e-05    -1.494000e-05   175.850252          0.000581   
3     2.630000e-07    -2.630000e-07   170.307565          0.000115   
4     3.761000e-06    -3.761000e-06   171.595550          0.001130   

   koi_time0bk_err2     ...      koi_steff_err2  koi_slogg  koi_slogg_err1  \
0         -0.002160     ...               -81.0      4.467           0.064   
1         -0.003520     ...               -81.0      4.467           0.064   
2         -0.000581     ...              -176.0      4.544           0.044   
3         -0.000115     ...              -174.0      4.564           0.053   
4         -0.001130     ...              -211.0      4.438           0.070   

   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0          -0.096     0.927          0.105         -0.061  291.93423   
1          -0.096     0.927          0.105         -0.061  291.93423   
2          -0.176     0.868          0.233         -0.078  297.00482   
3          -0.168     0.791          0.201         -0.067  285.53461   
4          -0.210     1.046          0.334         -0.133  288.75488   

         dec  koi_kepmag  
0  48.141651      15.347  
1  48.141651      15.347  
2  48.134129      15.436  
3  48.285210      15.597  
4  48.226200      15.509  

[5 rows x 40 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target,
                                                    train_size=80,
                                                    test_size=20,
                                                    random_state=24)

In [6]:
X_train.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
4979              0              0              0              0   23.133449   
2934              0              0              0              0   10.183182   
7244              1              0              0              0   75.072964   
1895              0              0              0              0   16.076731   
9415              1              0              1              1    3.044775   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
4979         0.000108        -0.000108    154.45296           0.00394   
2934         0.000098        -0.000098    133.21404           0.00752   
7244         0.004914        -0.004914    147.15910           0.03730   
1895         0.000065        -0.000065    143.39091           0.00337   
9415         0.000120        -0.000120    132.39750           0.03660   

      koi_time0bk_err2     ...      koi_steff_err2  koi_slogg  koi_slogg_err1  \
4979          -0.00394     ...              -170.0      4.382           0.189   
2934          -0.00752     ...              -127.0      4.421           0.040   
7244          -0.03730     ...              -215.0      4.325           0.086   
1895          -0.00337     ...              -195.0      4.498           0.052   
9415          -0.03660     ...              -159.0      4.591           0.035   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
4979          -0.231     0.932          0.291         -0.170  297.75192   
2934          -0.120     1.084          0.177         -0.071  287.97885   
7244          -0.373     1.248          0.855         -0.182  296.58698   
1895          -0.221     0.971          0.299         -0.100  288.47964   
9415          -0.112     0.780          0.132         -0.066  293.66754   

            dec  koi_kepmag  
4979  43.447578      14.656  
2934  42.679359      12.857  
7244  43.766918      12.236  
1895  47.101768      15.306  
9415  45.498451      15.964  

[5 rows x 40 columns]

# Pre-processing

Scale the data using the MinMaxScaler

In [7]:
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing

scaler = preprocessing.MinMaxScaler()
scaled_Xtrain = scaler.fit_transform(X_train)
scaled_Xtest = scaler.fit_transform(X_test)

print(scaler)
print(scaled_Xtrain)

MinMaxScaler(copy=True, feature_range=(0, 1))
[[0.         0.         0.         ... 0.89256582 0.42877819 0.7007217 ]
 [0.         0.         0.         ... 0.30073129 0.3712365  0.29499323]
 [1.         0.         0.         ... 0.82201974 0.45269763 0.15493911]
 ...
 [0.         1.         1.         ... 0.63727701 0.14733214 0.99142986]
 [0.         0.         0.         ... 0.08648788 0.21735944 0.80559314]
 [0.         0.         0.         ... 0.28372367 0.34572157 0.21402797]]


/anaconda3/envs/PythonData/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)
/anaconda3/envs/PythonData/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [8]:
#LabelEncoder()
#Encode classes for target data // not using thooo

#turning the target into a nurmerical value

le = preprocessing.LabelEncoder()
le.fit(target)

y_train_encoded = le.transform(y_train)
y_test_encoded = le.transform(y_test)

print(le.classes_)
print(y_test_encoded)
print(y_train_encoded)

['CANDIDATE' 'CONFIRMED' 'FALSE POSITIVE']
[2 1 2 2 2 1 0 1 2 1 1 0 0 1 2 0 2 2 2 2]
[0 0 2 1 2 0 2 0 0 1 2 2 0 2 0 1 0 1 1 2 0 0 1 1 0 0 0 1 1 2 0 1 2 2 0 2 2
 1 2 0 2 0 1 1 0 0 1 1 0 2 1 2 1 1 2 1 2 2 1 2 2 1 0 2 1 2 2 0 2 2 2 0 2 2
 2 0 1 2 0 1]


# Train the Support Vector Machine

In [9]:
from sklearn.svm import SVC 
from sklearn.metrics import classification_report

In [10]:
model12 = SVC(kernel='linear')
model12.fit(scaled_Xtrain, y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [11]:
#Refer to compare models
print(f"Training Data Score: {model12.score(scaled_Xtrain, y_train)}")
print(f"Testing Data Score: {model12.score(scaled_Xtest, y_test)}")

Training Data Score: 0.85
Testing Data Score: 0.75


# Hyperparameter Tuning

Use `GridSearchCV` to tune the `C` and `gamma` parameters

In [25]:

# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10, 50],
              'gamma': [0.0001, 0.0005, 0.001, 0.005]}
grid = GridSearchCV(model12, param_grid, verbose=3)

In [ ]:
# Train the model with GridSearch
grid.fit(X_train, y_train)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 16 candidates, totalling 48 fits
[CV] C=1, gamma=0.0001 ...............................................
[CV] ...... C=1, gamma=0.0001, score=0.4642857142857143, total=   6.7s
[CV] C=1, gamma=0.0001 ...............................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.7s remaining:    0.0s


[CV] ..................... C=1, gamma=0.0001, score=0.5, total=  17.1s
[CV] C=1, gamma=0.0001 ...............................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   23.8s remaining:    0.0s


[CV] ...... C=1, gamma=0.0001, score=0.5384615384615384, total=   1.5s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ...... C=1, gamma=0.0005, score=0.4642857142857143, total=   6.6s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ..................... C=1, gamma=0.0005, score=0.5, total=  16.9s
[CV] C=1, gamma=0.0005 ...............................................
[CV] ...... C=1, gamma=0.0005, score=0.5384615384615384, total=   1.5s
[CV] C=1, gamma=0.001 ................................................
[CV] ....... C=1, gamma=0.001, score=0.4642857142857143, total=   6.4s
[CV] C=1, gamma=0.001 ................................................
[CV] ...................... C=1, gamma=0.001, score=0.5, total=  16.8s
[CV] C=1, gamma=0.001 ................................................
[CV] ....... C=1, gamma=0.001, score=0.5384615384615384, total=   1.5s
[CV] C=1, gamma=0.005 ................................................
[CV] .

In [ ]:
print(grid2.best_params_)
print(grid2.best_score_)

## LOGISTIC REGRESSION


In [15]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
classifier.fit(scaled_Xtrain, y_train)

/anaconda3/envs/PythonData/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/envs/PythonData/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [17]:
#Refer to compare models
print(f"Training Data Score: {classifier.score(scaled_Xtrain, y_train)}")
print(f"Testing Data Score: {classifier.score(scaled_Xtest, y_test)}")

Training Data Score: 0.8375
Testing Data Score: 0.55


## DEEP LEARNING

In [18]:
from keras.utils import to_categorical

# One-hot encoding
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

Using TensorFlow backend.


ValueError: invalid literal for int() with base 10: 'CANDIDATE'

In [19]:
# first, create a normal neural network with 2 inputs, 6 hidden nodes, and 2 outputs
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(units=6, activation='relu', input_dim=40))
model.add(Dense(units=3, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [20]:

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 246       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 21        
Total params: 267
Trainable params: 267
Non-trainable params: 0
_________________________________________________________________


In [21]:

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [23]:

# Fit the model to the training data
model.fit(
    scaled_Xtrain,
    y_train_encoded,
    epochs=40,
    shuffle=True,
    verbose=2
)

Instructions for updating:
Use tf.cast instead.
Epoch 1/40
 - 0s - loss: 1.0999 - acc: 0.2750
Epoch 2/40
 - 0s - loss: 1.0966 - acc: 0.2875
Epoch 3/40
 - 0s - loss: 1.0938 - acc: 0.2875
Epoch 4/40
 - 0s - loss: 1.0915 - acc: 0.2625
Epoch 5/40
 - 0s - loss: 1.0892 - acc: 0.2750
Epoch 6/40
 - 0s - loss: 1.0875 - acc: 0.2750
Epoch 7/40
 - 0s - loss: 1.0852 - acc: 0.3125
Epoch 8/40
 - 0s - loss: 1.0833 - acc: 0.3500
Epoch 9/40
 - 0s - loss: 1.0812 - acc: 0.3625
Epoch 10/40
 - 0s - loss: 1.0792 - acc: 0.3625
Epoch 11/40
 - 0s - loss: 1.0770 - acc: 0.3625
Epoch 12/40
 - 0s - loss: 1.0748 - acc: 0.3750
Epoch 13/40
 - 0s - loss: 1.0725 - acc: 0.3875
Epoch 14/40
 - 0s - loss: 1.0699 - acc: 0.3875
Epoch 15/40
 - 0s - loss: 1.0673 - acc: 0.4000
Epoch 16/40
 - 0s - loss: 1.0650 - acc: 0.4250
Epoch 17/40
 - 0s - loss: 1.0625 - acc: 0.4375
Epoch 18/40
 - 0s - loss: 1.0599 - acc: 0.4500
Epoch 19/40
 - 0s - loss: 1.0575 - acc: 0.4500
Epoch 20/40
 - 0s - loss: 1.0547 - acc: 0.4500
Epoch 21/40
 - 0s - l